// data type in js

// string :> any carecter in '',""

// number: int, double, float

// boolean: true, false
//       0,1,2,3
// list [1,2,3, 'thish'] >
// length of list: 4

// object: '{key': 'value'}
// nan > not a number: NaN
// null :> we declare var without any value
// undefined : use a var without declaring

// var type declaration
// assign add value to variable
// name value 
// slways the data type of value will be assigned to variable
// var global scope : can bed access anyehere in the code
// var username = "ali"
// console.log(username)
// username = 10
// console.log(username)
// let local scope : can be access only in this block or function
// let phone = "0798467740"
// console.log(phone)
// const name1 = "Ahmad"
// console.log(name1)

// var name = value
// exmaples

// if // switch // for // while// do while
// function
// declare a function
// function funName(){
   // block code
// }
//call the function


// oop concepts : classes, objects, inheritance, polymorphism , encapsulation

// alert('you are trying to contact us)

// declare a var from html
// var contactButton = document.getElementById("contactButton")
// console.log(contactButton)
// function contactus(){  "contactus"
//     contactButton.innerHTML = "you contacted us"
//     contactButton.style.backgroundColor = "red"
// }

// function contactus() {"contactus"
//     alert('you are trying to contact us ')
// }
// contactus()

